spring.application.name=student-service

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true

# if COURSE_SERVICE_URL exists, use it. otherwise use http://localhost:8081
course.service.url=${COURSE_SERVICE_URL:http://localhost:8081}